# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
   push:
     branches: [ runtest-yaml ]
   pull_request:
     branches: [ runtest-yaml ]
     
   workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test -P single

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
          PERSONAL_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          
    - name: Post the link to the report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
         authToken: ${{secrets.ALLURE_TOKEN}}
         context: 'Test report'
         state: 'success'
         sha: ${{github.event.pull_request.head.sha || github.sha}}
         target_url: https://eyyupbagdas.github.io/socio-demo/${{ github.run_number }}
         
    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
         server_address: smtp.gmail.com
         server_port: 465
         username: socioqateams@gmail.com
         password: afmwncioqsabyljs
         subject: Github Actions job result
         to: eyyup@socio.events
         from: socioqateams@gmail.com
         body: https://eyyupbagdas.github.io/socio-demo/${{ github.run_number }}
         
    - name: Obtain a GitHub App Installation Access Token
      if: always()
      id: githubAppAuth
      run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"
    - name: Use the obtained token
      if: always()
      run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"context":"test","state":"success"}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA?access_token=$GITHUB_TOKEN"
      env:
          GITHUB_TOKEN: ${{ steps.githubAppAuth.outputs.token }}
          
    - name: Summary
      id: test
      uses: LouisBrunner/checks-action@v1.1.1
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test Result
        conclusion: ${{ job.status }}
        action_url: https://eyyupbagdas.github.io/socio-demo/${{ github.run_number }}
        details_url: https://eyyupbagdas.github.io/socio-demo/${{ github.run_number }}
        output: |
          {"summary":"https://eyyupbagdas.github.io/socio-demo/${{ github.run_number }}"}
        annotations: |
          [{"annotation_level":"success","title":"Allure test report link","message":"https://eyyupbagdas.github.io/socio-demo/${{ github.run_number }}"}]
        actions: |
          [{"label":"Click Me","description":"Click me to get free RAM","identifier":"https://eyyupbagdas.github.io/socio-demo/${{ github.run_number }}"}]
        images: |
          [{"alt":"Cool pic","image_url":"https://platform.socio.events/static/media/socio-logo-orange@1x.926e3cb3.png"}]
